const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const API_BASE_URL_PRIVATE = process.env.NEXT_PRIVATE_API_BASE_URL;
const PIXEL_ID = process.env.NEXT_PUBLIC_PIXEL_ID;

export { API_BASE_URL, API_BASE_URL_PRIVATE, PIXEL_ID };
