const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const API_BASE_URL_PRIVATE = process.env.NEXT_PRIVATE_API_BASE_URL;
const PIXEL_ID = process.env.NEXT_PUBLIC_PIXEL_ID;
const DOMAIN_WEB = process.env.NEXT_PUBLIC_DOMAIN_WEB;

export { API_BASE_URL, API_BASE_URL_PRIVATE, PIXEL_ID, DOMAIN_WEB };
